### ISSUE TITLE
500 on accessing a job in the career site for the first time

### ISSUE THREAD

**Issue by brotich** [canonical-web-and-design/canonical.com#194]
## Summary
- accessing a job description of on the https://canonical.com/careers page cause a 500 error

## Steps to reproduce
- got to the https://canonical.com/careers/ and follow the Engineering page
- click on a job to see its details

## What happens
- a 500 is raised as in the screenshot
<img width="1678" alt="Screenshot 2020-03-30 at 15 17 15" src="https://user-images.githubusercontent.com/23168146/77911531-a0b4fd00-7299-11ea-95f2-b963cd2469e7.png">

### Notes
- subsequent reloads of the same page load fine. i.e you see the information

**Comment by brotich** [comment]
maybe related to https://github.com/canonical-web-and-design/canonical.com/issues/193

**Comment by nottrobin** [comment]
Thanks for the report @brotich, we're now looking into this.

**Comment by nottrobin** [comment]
To update a little bit here - the error is:

```
ProxyError: HTTPSConnectionPool(host='boards-api.greenhouse.io', port=443): Max retries exceeded with url: /v1/boards/Canonical/jobs?content=true (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
```

The "Max retries exceeded" is a bit of a red herring, since in Requests the [default number of retries is 0](https://2.python-requests.org/en/latest/api/?highlight=max_retries#requests.adapters.HTTPAdapter). The pertinent part of the error is `ProxyError('Cannot connect to proxy.', timeout('timed out',))`. So it appears that the Greenhouse API we use is not responding in time.

We are [currently setting](https://github.com/canonical-web-and-design/canonicalwebteam.http/blob/master/canonicalwebteam/http/__init__.py#L62) the default timeout to be `(0.5, 3)`. But that module is deprecated and we no longer need to set timeouts on these requests, so I'm removing this mechanism in https://github.com/canonical-web-and-design/canonical.com/pull/195 which should hopefully fix the issue.
