### ISSUE TITLE
Back to list in career page doesn't work

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/canonical.com#483]
Go to https://canonical.com/careers/3761926/open-source-stack-software-engineering-lead-remote
Click back to list and see it takes up somewhere random.

**Comment by carkod** [comment]
It's taking me to https://canonical.com/careers/all? Where should it take you to otherwise?

**Comment by sowasred2012** [comment]
@ant did it take you to a different point on the page? Or to another URL entirely?

@carkod if you've come from https://canonical.com/careers/sales for example, it should send you back there, rather than /all. I think it's to do with: https://github.com/canonical-web-and-design/canonical.com/blob/main/templates/careers/job-detail.html#L54

```
<a href="{% if request.referrer %}{{ request.referrer }}{% else %}/careers/all{% endif %}" class="u-sv2">&lsaquo;&nbsp;Back to list</a>
```

I just tried it after clicking the link in the issue, and was taken to google.com. From the [Flask docs](https://flask.palletsprojects.com/en/2.0.x/api/#flask.Request.referrer):

> The Referer[sic] request-header field allows the client to specify, for the server’s benefit, the address (URI) of the resource from which the Request-URI was obtained (the “referrer”, although the header field is misspelled).

Can we check the referrer URI to see that it's actually a careers page we're sending them back to, or default to /careers/all?

**Comment by anthonydillon** [comment]
> Can we check the referrer URI to see that it's actually a careers page we're sending them back to, or default to /careers/all?

Yes, I think this logic is better.
